
import java.awt.event.MouseEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class AppointmentGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentGUI
     */
    private AppointmentModell model = new AppointmentModell();
    
    public AppointmentGUI() {
        initComponents();
        listOutput.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        popupOptionen = new javax.swing.JPopupMenu();
        menuOptionen = new javax.swing.JMenu();
        miHinzufügen = new javax.swing.JMenuItem();
        miLöschen = new javax.swing.JMenuItem();
        miÄndern = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOutput = new javax.swing.JList<>();

        menuOptionen.setLabel("Optionen");

        miHinzufügen.setLabel("Hinzufügen");
        miHinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHinzufügenActionPerformed(evt);
            }
        });
        menuOptionen.add(miHinzufügen);

        miLöschen.setLabel("Löschen");
        menuOptionen.add(miLöschen);

        miÄndern.setLabel("Ändern");
        menuOptionen.add(miÄndern);

        popupOptionen.add(menuOptionen);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Termine"));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, popupOptionen, org.jdesktop.beansbinding.ObjectProperty.create(), listOutput, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(listOutput);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miHinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHinzufügenActionPerformed
        AppointmentDlg dlg = new AppointmentDlg(this, true);
        dlg.setVisible(true);
        
        if( dlg.isOk() ){
            Appointment a = dlg.getAppointment();
            model.add(a);
        }
    }//GEN-LAST:event_miHinzufügenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOutput;
    private javax.swing.JMenu menuOptionen;
    private javax.swing.JMenuItem miHinzufügen;
    private javax.swing.JMenuItem miLöschen;
    private javax.swing.JMenuItem miÄndern;
    private javax.swing.JPopupMenu popupOptionen;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
